<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-14T18:47:56 IST" name="Default suite" finished-at="2024-03-14T18:48:17 IST" duration-ms="20943">
    <groups>
    </groups>
    <test started-at="2024-03-14T18:47:56 IST" name="Default test" finished-at="2024-03-14T18:48:17 IST" duration-ms="20943">
      <class name="com.qa.test.ValidFlightReservationTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.test.ValidFlightReservationTest@79e4c792]" started-at="2024-03-14T18:47:56 IST" name="setUp" finished-at="2024-03-14T18:48:04 IST" duration-ms="8286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="personalDetails()[pri:0, instance:com.qa.test.ValidFlightReservationTest@79e4c792]" started-at="2024-03-14T18:48:04 IST" name="personalDetails" finished-at="2024-03-14T18:48:09 IST" duration-ms="5083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personalDetails -->
        <test-method signature="flightDetails()[pri:1, instance:com.qa.test.ValidFlightReservationTest@79e4c792]" started-at="2024-03-14T18:48:09 IST" name="flightDetails" finished-at="2024-03-14T18:48:16 IST" duration-ms="7154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightDetails -->
        <test-method signature="bookingVerification()[pri:2, instance:com.qa.test.ValidFlightReservationTest@79e4c792]" started-at="2024-03-14T18:48:16 IST" name="bookingVerification" finished-at="2024-03-14T18:48:17 IST" duration-ms="352" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
First name doesn't match expected [Shankar] but found [Dolly]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
First name doesn't match expected [Shankar] but found [Dolly]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.qa.test.ValidFlightReservationTest.bookingVerification(ValidFlightReservationTest.java:304)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookingVerification -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.test.ValidFlightReservationTest@79e4c792]" started-at="2024-03-14T18:48:17 IST" name="tearDown" finished-at="2024-03-14T18:48:17 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.test.ValidFlightReservationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
